# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import pricelist, setting,receipt


class Ui_Homewindow(object):
    food_list = []
    
    def __init__(self,window):
        self.window=window
        
    def information(self,password,name):
        self.password= password
        self.username = name
        
    def open_pricelist(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = pricelist.Ui_PriceList()
        self.ui.setupUi(self.window)
        self.window.close()
        self.window.show()
    
    def homepage_to_setting(self):
        self.window.close()
        self.ui = setting.Ui_settings(self.window)
        self.window = QtWidgets.QDialog()
        self.ui.setupUi(self.window)
        self.window.show()
        
        
    def view_receipt(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = receipt.Ui_receipt()
        self.ui.setupUi(self.window)
        self.ui.display(self.tf1.text(), self.tf2.text(),self.totla_pay.text(), self.tf3.text(), self.tf4.text(),
                        self.tc1.text(),self.tc2.text(), self.tc3.text(),self.tc4.text(),self.tp1.text(),self.tp2.text(),self.tp3.text(),self.tp4.text(),
                        self.td1.text(),self.td2.text(),self.td3.text(),self.td4.text())
        # self.window.close()
        self.window.show()
    
        

    def cf1_function(self,cf1,tf1):
        if self.cf1.isChecked():
            self.tf1.setEnabled(True)
        else:
            self.tf1.setEnabled(False)
    def cf2_function(self,cf2,tf2):
        if self.cf2.isChecked():
            self.tf2.setEnabled(True)
            print("0")
        else:
            self.tf2.setEnabled(False)


    def cf3_function(self,cf3,tf3):
        if self.cf3.isChecked():
            self.tf3.setEnabled(True)
        else:
            self.tf3.setEnabled(False)
    def cf4_function(self,cf4,tf4):
        if self.cf4.isChecked():
            self.tf4.setEnabled(True)
        else:
            self.tf4.setEnabled(False)


    def cd1_function(self, cd1, td1):
        if self.cd1.isChecked():
            self.td1.setEnabled(True)
        else:
            self.td1.setEnabled(False)

    def cd2_function(self, cd2, td2):
        if self.cd2.isChecked():
            self.td2.setEnabled(True)
        else:
            self.td2.setEnabled(False)

    def cd3_function(self, cd3, td3):
        if self.cd3.isChecked():
            self.td3.setEnabled(True)
        else:
            self.td3.setEnabled(False)

    def cd4_function(self, cd4, td4):
        if self.cd4.isChecked():
            self.td4.setEnabled(True)
        else:
            self.td4.setEnabled(False)


    def cp1_function(self, cp1, tp1):
        if self.cp1.isChecked():
            self.tp1.setEnabled(True)
        else:
            self.tp1.setEnabled(False)

    def cp2_function(self, cp2, tp2):
        if self.cp2.isChecked():
            self.tp2.setEnabled(True)
        else:
            self.tp2.setEnabled(False)

    def cp3_function(self, cp3, tp3):
        if self.cp3.isChecked():
            self.tp3.setEnabled(True)
        else:
            self.tp3.setEnabled(False)

    def cp4_function(self, cp4, tp4):
        if self.cp4.isChecked():
            self.tp4.setEnabled(True)
        else:
            self.tp4.setEnabled(False)

    def cde1_function(self, cde1, tc1):
        if self.cde1.isChecked():
            self.tc1.setEnabled(True)
        else:
            self.tc1.setEnabled(False)

    def cde2_function(self, cde2, tc2):
        if self.cde2.isChecked():
            self.tc2.setEnabled(True)
        else:
            self.tc2.setEnabled(False)

    def cde3_function(self, cde3, tc3):
        if self.cde3.isChecked():
            self.tc3.setEnabled(True)
        else:
            self.tc3.setEnabled(False)

    def cde4_function(self, cde4, tc4):
        if self.cde4.isChecked():
            self.tc4.setEnabled(True)
        else:
            self.tc4.setEnabled(False)
                                       
    def cs1_function(self, cs1, ts1):
        if self.cs1.isChecked():
            self.ts1.setEnabled(True)
        else:
            self.ts1.setEnabled(False)

    def cs2_function(self, cs2, ts2):
        if self.cs2.isChecked():
            self.ts2.setEnabled(True)
        else:
            self.ts2.setEnabled(False)

    def cs3_function(self, cs3, ts3):
        if self.cs3.isChecked():
            self.ts3.setEnabled(True)
        else:
            self.ts3.setEnabled(False)

    def cs4_function(self, cs4, ts4):
        if self.cs4.isChecked():
            self.ts4.setEnabled(True)
        else:
            self.ts4.setEnabled(False)

    #################################
    def total_amount(self):
        item1 = float(self.tf1.text())
        item2 = float(self.tf2.text())
        # self.food_list.append("Bolanni")
        # self.food_list.append(item1)
        item3 = float(self.tf3.text())
        item4 = float(self.tf4.text())
        item5 = float(self.td1.text())
        item6 = float(self.td2.text())
        item7 = float(self.td3.text())
        item8 = float(self.td4.text())
        item9 = float(self.tp1.text())
        item10 =float(self.tp2.text())
        item11 = float(self.tp3.text())
        item12 = float(self.tp4.text())
        item13 = float(self.tc1.text())
        item14 = float(self.tc2.text())
        item15 = float(self.tc3.text())
        item16 = float(self.tc4.text())

        total = str((item1* 500)+(item2 *900)+(item3 * 450)+(item4*300)+ (item5 * 450)+(item6 * 600)+(item7 * 500) + (item8 * 280)+
                    (item13 * 400)+(item14 *350) +(item15 * 500) + (item16 *900)+ (item9 * 300) + (item10 * 550)+ (item11 * 500)+
                    (item12 * 150))

        self.totla_pay.setText(total)
        ####################################### RESET ##########################################

    def reset_button(self):
            ######################################### CHECKBOXES ##############################
            self.cd1.setChecked(False)
            self.cd2.setChecked(False)
            self.cd3.setChecked(False)
            self.cd4.setChecked(False)

            self.cf1.setChecked(False)
            self.cf2.setChecked(False)
            self.cf3.setChecked(False)
            self.cf4.setChecked(False)

            self.cp1.setChecked(False)
            self.cp2.setChecked(False)
            self.cp3.setChecked(False)
            self.cp4.setChecked(False)

            self.cs1.setChecked(False)
            self.cs2.setChecked(False)
            self.cs3.setChecked(False)
            self.cs4.setChecked(False)

            self.cde1.setChecked(False)
            self.cde2.setChecked(False)
            self.cde3.setChecked(False)
            self.cde4.setChecked(False)
            
            ################
            self.totla_pay.setText("0")

            ###################################### LINE EDITS##########################################

            self.tf1.setEnabled(False)
            self.tf1.setText("0")

            self.tf2.setEnabled(False)
            self.tf2.setText("0")

            self.tf3.setEnabled(False)
            self.tf3.setText("0")

            self.tf4.setEnabled(False)
            self.tf4.setText("0")

            self.td1.setEnabled(False)
            self.td1.setText("0")

            self.td2.setEnabled(False)
            self.td2.setText("0")

            self.td3.setEnabled(False)
            self.td3.setText("0")

            self.td4.setEnabled(False)
            self.td4.setText("0")

            self.tp1.setEnabled(False)
            self.tp1.setText("0")

            self.tp2.setEnabled(False)
            self.tp2.setText("0")

            self.tp3.setEnabled(False)
            self.tp3.setText("0")

            self.tp4.setEnabled(False)
            self.tp4.setText("0")

            self.tc1.setEnabled(False)
            self.tc1.setText("0")

            self.tc2.setEnabled(False)
            self.tc2.setText("0")

            self.tc3.setEnabled(False)
            self.tc3.setText("0")

            self.tc4.setEnabled(False)
            self.tc4.setText("0")

            self.ts1.setEnabled(False)
            self.ts1.setText("0")

            self.ts2.setEnabled(False)
            self.ts2.setText("0")

            self.ts3.setEnabled(False)
            self.ts3.setText("0")

            self.ts4.setEnabled(False)
            self.ts4.setText("0")
            
        
    def setupUi(self, Homewindow):
        Homewindow.setObjectName("Homewindow")
        Homewindow.resize(1257, 702)
        self.centralwidget = QtWidgets.QWidget(Homewindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 40, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica Rounded")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(137, 28, 28);\n"
"font: 75 20pt \"Helvetica Rounded\";")
        self.label_2.setObjectName("label_2")
        self.foodframe = QtWidgets.QFrame(self.centralwidget)
        self.foodframe.setGeometry(QtCore.QRect(10, 120, 1211, 491))
        self.foodframe.setStyleSheet(".QFrame{\n"
"border-radius: 10px;\n"
"border: 3px solid #891c1c;\n"
"}")
        self.foodframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foodframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.foodframe.setLineWidth(8)
        self.foodframe.setMidLineWidth(8)
        self.foodframe.setObjectName("foodframe")
        self.cf1 = QtWidgets.QCheckBox(self.foodframe)
        self.cf1.setGeometry(QtCore.QRect(570, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cf1.setFont(font)
        self.cf1.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cf1.setObjectName("cf1")
        self.cf2 = QtWidgets.QCheckBox(self.foodframe)
        self.cf2.setGeometry(QtCore.QRect(940, 140, 141, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cf2.setFont(font)
        self.cf2.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cf2.setObjectName("cf2")
        self.cf3 = QtWidgets.QCheckBox(self.foodframe)
        self.cf3.setGeometry(QtCore.QRect(940, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cf3.setFont(font)
        self.cf3.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cf3.setObjectName("cf3")
        self.cf4 = QtWidgets.QCheckBox(self.foodframe)
        self.cf4.setGeometry(QtCore.QRect(940, 260, 121, 31))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cf4.setFont(font)
        self.cf4.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cf4.setObjectName("cf4")
        self.tf4 = QtWidgets.QLineEdit(self.foodframe)
        self.tf4.setEnabled(False)
        self.tf4.setGeometry(QtCore.QRect(1080, 260, 71, 31))
        self.tf4.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tf4.setObjectName("tf4")
        self.tf1 = QtWidgets.QLineEdit(self.foodframe)
        self.tf1.setEnabled(False)
        self.tf1.setGeometry(QtCore.QRect(740, 140, 71, 31))
        self.tf1.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tf1.setObjectName("tf1")
        self.tf2 = QtWidgets.QLineEdit(self.foodframe)
        self.tf2.setEnabled(False)
        self.tf2.setGeometry(QtCore.QRect(1090, 140, 71, 31))
        self.tf2.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tf2.setObjectName("tf2")
        self.tf3 = QtWidgets.QLineEdit(self.foodframe)
        self.tf3.setEnabled(False)
        self.tf3.setGeometry(QtCore.QRect(1090, 180, 71, 31))
        self.tf3.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tf3.setObjectName("tf3")
        self.tc1 = QtWidgets.QLineEdit(self.foodframe)
        self.tc1.setEnabled(False)
        self.tc1.setGeometry(QtCore.QRect(1050, 350, 71, 31))
        self.tc1.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tc1.setObjectName("tc1")
        self.cde1 = QtWidgets.QCheckBox(self.foodframe)
        self.cde1.setGeometry(QtCore.QRect(870, 350, 161, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cde1.setFont(font)
        self.cde1.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cde1.setObjectName("cde1")
        self.cde4 = QtWidgets.QCheckBox(self.foodframe)
        self.cde4.setGeometry(QtCore.QRect(940, 80, 151, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cde4.setFont(font)
        self.cde4.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cde4.setObjectName("cde4")
        self.cde2 = QtWidgets.QCheckBox(self.foodframe)
        self.cde2.setGeometry(QtCore.QRect(940, 40, 181, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cde2.setFont(font)
        self.cde2.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cde2.setObjectName("cde2")
        self.tc2 = QtWidgets.QLineEdit(self.foodframe)
        self.tc2.setEnabled(False)
        self.tc2.setGeometry(QtCore.QRect(1110, 40, 71, 31))
        self.tc2.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tc2.setObjectName("tc2")
        self.tc4 = QtWidgets.QLineEdit(self.foodframe)
        self.tc4.setEnabled(False)
        self.tc4.setGeometry(QtCore.QRect(1110, 80, 71, 31))
        self.tc4.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tc4.setObjectName("tc4")
        self.cde3 = QtWidgets.QCheckBox(self.foodframe)
        self.cde3.setGeometry(QtCore.QRect(570, 340, 91, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cde3.setFont(font)
        self.cde3.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cde3.setObjectName("cde3")
        self.tc3 = QtWidgets.QLineEdit(self.foodframe)
        self.tc3.setEnabled(False)
        self.tc3.setGeometry(QtCore.QRect(680, 340, 71, 31))
        self.tc3.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tc3.setObjectName("tc3")
        self.cd1 = QtWidgets.QCheckBox(self.foodframe)
        self.cd1.setGeometry(QtCore.QRect(270, 140, 181, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cd1.setFont(font)
        self.cd1.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cd1.setObjectName("cd1")
        self.cd2 = QtWidgets.QCheckBox(self.foodframe)
        self.cd2.setGeometry(QtCore.QRect(270, 190, 201, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cd2.setFont(font)
        self.cd2.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cd2.setObjectName("cd2")
        self.td4 = QtWidgets.QLineEdit(self.foodframe)
        self.td4.setEnabled(False)
        self.td4.setGeometry(QtCore.QRect(440, 260, 71, 31))
        self.td4.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.td4.setObjectName("td4")
        self.cd3 = QtWidgets.QCheckBox(self.foodframe)
        self.cd3.setGeometry(QtCore.QRect(570, 190, 161, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cd3.setFont(font)
        self.cd3.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cd3.setObjectName("cd3")
        self.td3 = QtWidgets.QLineEdit(self.foodframe)
        self.td3.setEnabled(False)
        self.td3.setGeometry(QtCore.QRect(740, 190, 71, 31))
        self.td3.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.td3.setObjectName("td3")
        self.cd4 = QtWidgets.QCheckBox(self.foodframe)
        self.cd4.setGeometry(QtCore.QRect(270, 260, 161, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cd4.setFont(font)
        self.cd4.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cd4.setObjectName("cd4")
        self.td2 = QtWidgets.QLineEdit(self.foodframe)
        self.td2.setEnabled(False)
        self.td2.setGeometry(QtCore.QRect(460, 190, 71, 31))
        self.td2.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.td2.setObjectName("td2")
        self.td1 = QtWidgets.QLineEdit(self.foodframe)
        self.td1.setEnabled(False)
        self.td1.setGeometry(QtCore.QRect(460, 140, 71, 31))
        self.td1.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.td1.setObjectName("td1")
        self.ts4 = QtWidgets.QLineEdit(self.foodframe)
        self.ts4.setEnabled(False)
        self.ts4.setGeometry(QtCore.QRect(680, 390, 71, 31))
        self.ts4.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.ts4.setObjectName("ts4")
        self.ts2 = QtWidgets.QLineEdit(self.foodframe)
        self.ts2.setEnabled(False)
        self.ts2.setGeometry(QtCore.QRect(430, 340, 71, 31))
        self.ts2.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.ts2.setObjectName("ts2")
        self.ts1 = QtWidgets.QLineEdit(self.foodframe)
        self.ts1.setEnabled(False)
        self.ts1.setGeometry(QtCore.QRect(690, 260, 71, 31))
        self.ts1.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.ts1.setObjectName("ts1")
        self.cs3 = QtWidgets.QCheckBox(self.foodframe)
        self.cs3.setGeometry(QtCore.QRect(270, 390, 151, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cs3.setFont(font)
        self.cs3.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cs3.setObjectName("cs3")
        self.cs1 = QtWidgets.QCheckBox(self.foodframe)
        self.cs1.setGeometry(QtCore.QRect(570, 260, 111, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cs1.setFont(font)
        self.cs1.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cs1.setObjectName("cs1")
        self.ts3 = QtWidgets.QLineEdit(self.foodframe)
        self.ts3.setEnabled(False)
        self.ts3.setGeometry(QtCore.QRect(430, 390, 71, 31))
        self.ts3.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.ts3.setObjectName("ts3")
        self.cs4 = QtWidgets.QCheckBox(self.foodframe)
        self.cs4.setGeometry(QtCore.QRect(570, 400, 101, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cs4.setFont(font)
        self.cs4.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cs4.setObjectName("cs4")
        self.cs2 = QtWidgets.QCheckBox(self.foodframe)
        self.cs2.setGeometry(QtCore.QRect(270, 340, 151, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cs2.setFont(font)
        self.cs2.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cs2.setObjectName("cs2")
        self.tp1 = QtWidgets.QLineEdit(self.foodframe)
        self.tp1.setEnabled(False)
        self.tp1.setGeometry(QtCore.QRect(430, 30, 71, 31))
        self.tp1.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tp1.setObjectName("tp1")
        self.cp2 = QtWidgets.QCheckBox(self.foodframe)
        self.cp2.setGeometry(QtCore.QRect(270, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cp2.setFont(font)
        self.cp2.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cp2.setObjectName("cp2")
        self.tp4 = QtWidgets.QLineEdit(self.foodframe)
        self.tp4.setEnabled(False)
        self.tp4.setGeometry(QtCore.QRect(750, 80, 71, 31))
        self.tp4.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tp4.setObjectName("tp4")
        self.cp1 = QtWidgets.QCheckBox(self.foodframe)
        self.cp1.setGeometry(QtCore.QRect(270, 30, 151, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cp1.setFont(font)
        self.cp1.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cp1.setObjectName("cp1")
        self.cp3 = QtWidgets.QCheckBox(self.foodframe)
        self.cp3.setGeometry(QtCore.QRect(570, 40, 181, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cp3.setFont(font)
        self.cp3.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cp3.setObjectName("cp3")
        self.tp2 = QtWidgets.QLineEdit(self.foodframe)
        self.tp2.setEnabled(False)
        self.tp2.setGeometry(QtCore.QRect(430, 70, 71, 31))
        self.tp2.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tp2.setObjectName("tp2")
        self.cp4 = QtWidgets.QCheckBox(self.foodframe)
        self.cp4.setGeometry(QtCore.QRect(570, 80, 171, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cp4.setFont(font)
        self.cp4.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.cp4.setObjectName("cp4")
        self.tp3 = QtWidgets.QLineEdit(self.foodframe)
        self.tp3.setEnabled(False)
        self.tp3.setGeometry(QtCore.QRect(750, 40, 71, 31))
        self.tp3.setStyleSheet("QLineEdit{\n"
"border-radius : 30px;\n"
"border:3px solid #891c1c;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tp3.setObjectName("tp3")
        self.label_3 = QtWidgets.QLabel(self.foodframe)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica Rounded")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 20pt \"Helvetica Rounded\";\n"
"color: rgb(137, 28, 28);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.foodframe)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica Rounded")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 20pt \"Helvetica Rounded\";\n"
"color: rgb(137, 28, 28);")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.foodframe)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica Rounded")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 75 20pt \"Helvetica Rounded\";\n"
"color: rgb(137, 28, 28);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.foodframe)
        self.label_7.setGeometry(QtCore.QRect(10, 320, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica Rounded")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 75 20pt \"Helvetica Rounded\";\n"
"color: rgb(137, 28, 28);")
        self.label_7.setObjectName("label_7")
        self.totla_pay = QtWidgets.QLineEdit(self.foodframe)
        self.totla_pay.setGeometry(QtCore.QRect(860, 390, 281, 51))
        font = QtGui.QFont()
        font.setFamily("red")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.totla_pay.setFont(font)
        self.totla_pay.setStyleSheet("QLineEdit{\n"
"border-radius : 25px;\n"
"border:3px solid #891c1c;\n"
"font: 15px red ;\n"
"padding-left: 10px;\n"
"}")
        self.totla_pay.setObjectName("totla_pay")
        self.label = QtWidgets.QLabel(self.foodframe)
        self.label.setGeometry(QtCore.QRect(790, 410, 55, 16))
        self.label.setStyleSheet("font: 11pt \"High Tower Text\";")
        self.label.setObjectName("label")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -210, 1411, 931))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.background.setFont(font)
        self.background.setStyleSheet("QLabel{\n"
"    background-color: #f7f1eb;\n"
"}")
        self.background.setText("")
        self.background.setObjectName("background")
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(1150, 40, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.setting.setFont(font)
        self.setting.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.setting.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/settings-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting.setIcon(icon)
        self.setting.setIconSize(QtCore.QSize(35, 35))
        self.setting.setObjectName("setting")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1060, 0, 191, 321))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../images/pride-pattern-right.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 201, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../images/logo-01.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pricelist = QtWidgets.QPushButton(self.centralwidget)
        self.pricelist.setGeometry(QtCore.QRect(60, 630, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pricelist.setFont(font)
        self.pricelist.setStyleSheet("QPushButton{\n"
"background-color: #fdefe6;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #white;\n"
"border-style:inset;\n"
"}\n"
"\n"
"")
        self.pricelist.setObjectName("pricelist")
        self.receipt = QtWidgets.QPushButton(self.centralwidget)
        self.receipt.setGeometry(QtCore.QRect(370, 630, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.receipt.setFont(font)
        self.receipt.setStyleSheet("QPushButton{\n"
"background-color: #fdefe6;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #white;\n"
"border-style:inset;\n"
"}\n"
"\n"
"")
        self.receipt.setObjectName("receipt")
        self.total = QtWidgets.QPushButton(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(730, 630, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.total.setFont(font)
        self.total.setStyleSheet("QPushButton{\n"
"background-color: #fdefe6;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #white;\n"
"border-style:inset;\n"
"}\n"
"\n"
"")
        self.total.setObjectName("total")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(960, 630, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.reset.setFont(font)
        self.reset.setStyleSheet("QPushButton{\n"
"background-color: #fdefe6;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #white;\n"
"border-style:inset;\n"
"}\n"
"\n"
"")
        self.reset.setObjectName("reset")
        self.background.raise_()
        self.label_8.raise_()
        self.foodframe.raise_()
        self.label_2.raise_()
        self.setting.raise_()
        self.label_5.raise_()
        self.pricelist.raise_()
        self.receipt.raise_()
        self.total.raise_()
        self.reset.raise_()
                ###########################ACTION################
        self.cs4.stateChanged.connect(lambda: self.cs4_function(self.cs4, self.ts4))
        ################################################
        ###########################ACTION################
        self.cd3.stateChanged.connect(lambda: self.cd3_function(self.cd3, self.td3))
        self.setting.clicked.connect(self.homepage_to_setting)
        ################################################
        ####Action###################################
        #self.exit.clicked.connect(self.exit_action)
        #############################################
        ####Action##############################################
        #self.signout.clicked.connect(self.openlogin_signout)
        ###########################################################
        
        ####Action####
        self.reset.clicked.connect(self.reset_button)
        ##############
        ####Action####
        self.total.clicked.connect(self.total_amount)
        ##############
        ####Action####
        self.receipt.clicked.connect(self.view_receipt)
        ##############
        ####Action#########################################
        self.pricelist.clicked.connect(self.open_pricelist)
        ####################################################
        ###########################ACTION################
        self.cde4.stateChanged.connect(lambda: self.cde4_function(self.cde4, self.tc4))
        ################################################
        ###########################ACTION################
        self.cde3.stateChanged.connect(lambda: self.cde3_function(self.cde3, self.tc3))
        ################################################
        ###########################ACTION################
        self.cde2.stateChanged.connect(lambda: self.cde2_function(self.cde2, self.tc2))
        ################################################
        ###########################ACTION################
        self.cde1.stateChanged.connect(lambda: self.cde1_function(self.cde1, self.tc1))
        ################################################
        ###########################ACTION################
        self.cp4.stateChanged.connect(lambda: self.cp4_function(self.cp4, self.tp4))
        ################################################
        ###########################ACTION################
        self.cp3.stateChanged.connect(lambda: self.cp3_function(self.cp3, self.tp3))
        ################################################
        ###########################ACTION################
        self.cp2.stateChanged.connect(lambda: self.cp2_function(self.cp2, self.tp2))
        ################################################
        ###########################ACTION################
        self.cp1.stateChanged.connect(lambda: self.cp1_function(self.cp1, self.tp1))
        ################################################
        ###########################ACTION################
        self.cd4.stateChanged.connect(lambda: self.cd4_function(self.cd4, self.td4))
        ################################################
        ###########################ACTION################
        self.cd2.stateChanged.connect(lambda: self.cd2_function(self.cd2, self.td2))
        ################################################
        ###########################ACTION################
        self.cd1.stateChanged.connect(lambda: self.cd1_function(self.cd1, self.td1))
        ################################################
        ###########################ACTION################
        self.cf4.stateChanged.connect(lambda: self.cf4_function(self.cf4, self.tf4))
        ################################################
        ###########################ACTION################
        self.cf3.stateChanged.connect(lambda: self.cf3_function(self.cf3, self.tf3))
        ################################################
        ###########################ACTION################
        self.cf2.stateChanged.connect(lambda: self.cf2_function(self.cf2, self.tf2))
        ################################################
        ###########################ACTION################
        self.cf1.stateChanged.connect(lambda:self.cf1_function(self.cf1,self.tf1))
        ################################################
        
######################################
        ###########################################
        self.cs3.stateChanged.connect(lambda: self.cs3_function(self.cs3, self.ts3))
        ################################################
        ###########################ACTION################
        self.cs2.stateChanged.connect(lambda: self.cs2_function(self.cs2, self.ts2))
        ################################################
        ###########################ACTION################
        self.cs1.stateChanged.connect(lambda: self.cs1_function(self.cs1, self.ts1))
        ################################################
        Homewindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Homewindow)
        QtCore.QMetaObject.connectSlotsByName(Homewindow)

    def retranslateUi(self, Homewindow):
        _translate = QtCore.QCoreApplication.translate
        Homewindow.setWindowTitle(_translate("Homewindow", "MainWindow"))
        self.label_2.setText(_translate("Homewindow", "Welcome to the Nando\'s Restaurent"))
        self.cf1.setText(_translate("Homewindow", "Nandoca\'s Choice"))
        self.cf2.setText(_translate("Homewindow", "Chicken Breast Pita"))
        self.cf3.setText(_translate("Homewindow", "Thigh and Mighty"))
        self.cf4.setText(_translate("Homewindow", "Veggie Burger"))
        self.tf4.setPlaceholderText(_translate("Homewindow", "0"))
        self.tf1.setPlaceholderText(_translate("Homewindow", "0"))
        self.tf2.setPlaceholderText(_translate("Homewindow", "0"))
        self.tf3.setPlaceholderText(_translate("Homewindow", "0"))
        self.tc1.setPlaceholderText(_translate("Homewindow", "0"))
        self.cde1.setText(_translate("Homewindow", "Green Side Salad"))
        self.cde4.setText(_translate("Homewindow", "Cheese Cake"))
        self.cde2.setText(_translate("Homewindow", "PERi-PERi Wings"))
        self.tc2.setPlaceholderText(_translate("Homewindow", "0"))
        self.tc4.setPlaceholderText(_translate("Homewindow", "0"))
        self.cde3.setText(_translate("Homewindow", "Full Platter"))
        self.tc3.setPlaceholderText(_translate("Homewindow", "0"))
        self.cd1.setText(_translate("Homewindow", "PERi-PERi Chicken Bow"))
        self.cd2.setText(_translate("Homewindow", "Avocado Pepper Bowl"))
        self.td4.setPlaceholderText(_translate("Homewindow", "0"))
        self.cd3.setText(_translate("Homewindow", "Chicken Caesar Wrap"))
        self.td3.setPlaceholderText(_translate("Homewindow", "0"))
        self.cd4.setText(_translate("Homewindow", "Portobello Mushroom"))
        self.td2.setPlaceholderText(_translate("Homewindow", "0"))
        self.td1.setPlaceholderText(_translate("Homewindow", "0"))
        self.ts4.setPlaceholderText(_translate("Homewindow", "0"))
        self.ts2.setPlaceholderText(_translate("Homewindow", "0"))
        self.ts1.setPlaceholderText(_translate("Homewindow", "0"))
        self.cs3.setText(_translate("Homewindow", "Mashed Potato"))
        self.cs1.setText(_translate("Homewindow", "Halloumi Wrap"))
        self.ts3.setPlaceholderText(_translate("Homewindow", "0"))
        self.cs4.setText(_translate("Homewindow", "Coleslaw"))
        self.cs2.setText(_translate("Homewindow", "Jumbo Chicken Platter"))
        self.tp1.setPlaceholderText(_translate("Homewindow", "0"))
        self.cp2.setText(_translate("Homewindow", "1/4 Chicken - Breast"))
        self.tp4.setPlaceholderText(_translate("Homewindow", "0"))
        self.cp1.setText(_translate("Homewindow", "1/2 Chicken"))
        self.cp3.setText(_translate("Homewindow", "Chicken Thigh Skewers"))
        self.tp2.setPlaceholderText(_translate("Homewindow", "0"))
        self.cp4.setText(_translate("Homewindow", "Boneless Chicken Breast"))
        self.tp3.setPlaceholderText(_translate("Homewindow", "0"))
        self.label_3.setText(_translate("Homewindow", "PERi-PERi Chicken"))
        self.label_4.setText(_translate("Homewindow", "Nando\'s Favorites"))
        self.label_6.setText(_translate("Homewindow", "Veg PERidise"))
        self.label_7.setText(_translate("Homewindow", "Sharing Platters"))
        self.totla_pay.setPlaceholderText(_translate("Homewindow", "0"))
        self.label.setText(_translate("Homewindow", "Total:"))
        self.pricelist.setText(_translate("Homewindow", "Price List"))
        self.receipt.setText(_translate("Homewindow", "Generate Receipt"))
        self.total.setText(_translate("Homewindow", "Total"))
        self.reset.setText(_translate("Homewindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Homewindow = QtWidgets.QMainWindow()
    ui = Ui_Homewindow(Homewindow)
    ui.setupUi(Homewindow)
    Homewindow.show()
    sys.exit(app.exec_())
